{"name": "实名认证", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'url'", "trace": "@pytest.fixture(scope='session')\n    def token():\n        url='http://qa.yansl.com:8084/login'\n        req={\n             \"pwd\": \"123456zjc\",\n             \"userName\": \"123zjc\"\n            }\n>       resp = request_tool.post_json(url, json=req)\n\ntest_case\\conftest.py:10: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nargs = ('http://qa.yansl.com:8084/login',)\nkwargs = {'json': {'pwd': '123456zjc', 'userName': '123zjc'}}, r = ()\n\n    def _func(*args, **kwargs):\n        r= func(*args, **kwargs)\n        request = \"-------------------request-------------\" \\\n>                 \"\\n{0}\\n{1}\\n{2}\".format(r.url, string_tool.dic_to_str(r.request.headers), r.request.body)\nE       AttributeError: 'tuple' object has no attribute 'url'\n\ntools\\report\\decorators_tool.py:11: AttributeError"}, "attachments": [{"name": "log", "source": "f5826671-7ed0-4410-b44b-0cd07f42c1a2-attachment.txt", "type": "text/plain"}], "start": 1602685046332, "stop": 1602685046332, "uuid": "f1fe01a4-0d56-4af8-92a2-f515c73f4683", "historyId": "d6666fcad673fa0ef5e5af13237f96e1", "fullName": "test_case.User.test_realname#test_realname", "labels": [{"name": "parentSuite", "value": "test_case.User"}, {"name": "suite", "value": "test_realname"}, {"name": "subSuite"}, {"name": "host", "value": "DESKTOP-679Q8H2"}, {"name": "thread", "value": "4200-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case.User.test_realname"}]}