ERROR    tools.report.log_tool:log_tool.py:52 Exception url: http://qa.yansl.com:8084/login
ERROR    tools.report.log_tool:log_tool.py:52 HTTPConnectionPool(host='127.0.0.1', port=7890): Max retries exceeded with url: http://qa.yansl.com:8084/login (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response')))